# NumPy Basics: Arrays and Vectorized Computation
# NumPy 基础：数组和矢量计算

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 14 ms, sys: 5.02 ms, total: 19 ms
Wall time: 23.4 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 554 ms, sys: 125 ms, total: 679 ms
Wall time: 680 ms


> 基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少

## 4.1 NumPy的ndarray：一种多维数组对象

In [4]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.30336351, -0.54625205, -0.52694154],
       [ 0.22307203, -0.88116372, -0.26765029]])

In [5]:
# 所有的元素都乘以10
data * 10

array([[-3.03363513, -5.46252051, -5.26941542],
       [ 2.23072028, -8.81163722, -2.67650287]])

In [6]:
# 每个元素都与自身相加
data + data

array([[-0.60672703, -1.0925041 , -1.05388308],
       [ 0.44614406, -1.76232744, -0.53530057]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

### 创建ndarray

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int64')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
np.empty((2, 3, 2))

array([[[2.31584178e+077, 2.31584178e+077],
        [4.94065646e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [29]:
# arange是Python内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

数组创建函数  
![数组创建函数](https://wizardforcel.gitbooks.io/pyda-2e/content/img/7178691-78ab11f67e7077a6.png)