In [1]:
import numpy as np

In [15]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.concatenate((arr1, arr2), axis=0)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.random.uniform(0.0, 5.0, size=(2, 3))

array([[2.48579164, 1.97487755, 1.49312849],
       [1.99325643, 1.20200611, 0.24509413]])

### 同じ要素の数列を作る

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(2)

array([1., 1.])

In [21]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 单位行列

In [22]:
# 対角要素
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# 指定要素
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [24]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [25]:
np.nan

nan

In [26]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

### 範囲指定で均等割りデータを作る

In [27]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

 ### 要素間の差分

In [30]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

### 連結

In [32]:
a = np.array([1, 5, 4])
a1 = a
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [39]:
b = np.array([[1, 2, 8], [4, 5, 8]])
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [42]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [43]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [44]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [46]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割

In [48]:
first, second = np.hsplit(b3, [2])

In [49]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [50]:
second

array([[ 8],
       [ 8],
       [45]])

In [51]:
first1, second1 = np.vsplit(b3, [2])
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [52]:
second1

array([[30, 60, 45]])

### 転置

In [53]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [54]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

### 次元追加

In [55]:
a

array([1, 5, 4])

In [56]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [57]:
a[:, np.newaxis]

array([[1],
       [5],
       [4]])

### グリッドデータの生成

In [58]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [60]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [61]:
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [62]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [63]:
l = np.meshgrid(m, n)
l

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]), array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])]

## 4.1.3 Numpyの各機能

In [69]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [70]:
print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)
print("e:", e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


### ユニバーサルファンクション

In [71]:
li = [[-3, -2, -1], [0, 1, 2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [72]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [74]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [77]:
np.log(a)

/Users/charlielee/anaconda3/envs/data/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [78]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [79]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

### ブロードキャスト

In [80]:
a

array([0, 1, 2])

In [81]:
a + 10

array([10, 11, 12])

In [82]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [83]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [84]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [85]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [86]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [89]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [90]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [91]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [92]:
b - a 

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [93]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [94]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [95]:
c / a

/Users/charlielee/anaconda3/envs/data/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

### ドット積

In [96]:
np.dot(b, a)

array([-4,  5])

In [97]:
b @ a

array([-4,  5])

In [101]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [102]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### 判定・論理値

In [103]:
a > 1

array([False, False,  True])

In [105]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [106]:
np.count_nonzero(b > 0)

2

In [107]:
np.sum(b > 0)

2

In [108]:
np.any(b > 0)

True

In [109]:
np.all(b > 0)

False

In [110]:
b[b > 0]

array([1, 2])

In [111]:
b == c

array([[False, False, False],
       [False, False, False]])

In [112]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [114]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [115]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [116]:
np.allclose(b, c, atol=10)

True

### 関数とメソッド

In [117]:
np.sum(a)

3

In [118]:
a.sum()

3